#ifndef LOGOS_MODULE_IMPL_H
#define LOGOS_MODULE_IMPL_H

/* ===========================================================================
 * logos_module_impl.h — the COMMON module-impl C ABI.
 *
 * ONE contract for module implementations in every language: a Logos module
 * compiles to a cdylib exporting exactly these symbols. The C++ SDK emits
 * this wrapper around a universal C++ impl class; the Rust SDK emits it
 * around a Rust impl. The uniform generated Qt-plugin glue (and, later, a
 * no-Qt host) talks to the cdylib ONLY through this ABI — the glue is
 * identical regardless of the module's source language, which is what makes
 * the eventual Qt-glue removal a host swap instead of a per-language change.
 *
 * Data model mirrors the lp_* consumer ABI (logos_protocol.h):
 *   - method args / event payloads: JSON array (UTF-8 const char*)
 *   - results: JSON value
 *   - bytes: the canonical {"_bytes":"<base64url>"} tagged form
 *   - errors from dispatch: NULL return, or a canonical error object
 *     {"code","message","origin"} returned as the result of a failed call
 *     when the implementation prefers structured errors.
 *
 * Ownership: every char* RETURNED by the module is heap-allocated and the
 * CALLER frees it with logos_module_string_free (exported by the module so
 * allocator domains never mix). Every const char* passed IN is borrowed.
 * The one exception is the token bridge (logos_module_set_token_bridge): its
 * get_token callback returns a HOST-allocated string, which the module frees
 * by calling the bridge's own free_fn — symmetric to logos_module_string_free
 * but for the host's allocator, so the two domains still never mix.
 *
 * Threading: the host serializes dispatch calls (one at a time) unless a
 * future capability negotiates otherwise. The emit callback may be invoked
 * from any module thread; the host marshals.
 *
 * Versioning: logos_module_get_protocol_version() returns the
 * logos-protocol semver the module was COMPILED against (forwarded from
 * LOGOS_PROTOCOL_VERSION_STRING, never minted). Hosts apply the same rule
 * as the metadata stamp: equal MAJOR ⇔ compatible. This runtime handshake
 * complements the build-time metadata stamp and is what a no-Qt host (no
 * Qt plugin metadata) negotiates with.
 * =========================================================================== */

#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WIN32)
#define LOGOS_MODULE_IMPL_EXPORT __declspec(dllexport)
#else
#define LOGOS_MODULE_IMPL_EXPORT __attribute__((visibility("default")))
#endif

/* Event-emission callback installed by the host/glue. `data_json` is a JSON
 * array payload, borrowed for the duration of the call. */
typedef void (*logos_module_emit_cb)(const char* event_name,
                                     const char* data_json,
                                     void* user_data);

/* ---------------------------------------------------------------------------
 * Token bridge (opt-in) — host services a token-authority module reaches back
 * into. Only capability_module needs this: it must read the host's token store
 * and inform an ARBITRARY target module of a caller's token, neither of which
 * the Qt-free cdylib impl can do on its own. The host installs these function
 * pointers via logos_module_set_token_bridge; the module (through the
 * LogosTokenManagerContext SDK base) calls them. All const char* IN are
 * borrowed; get_token's returned char* is HOST-allocated and freed by free_fn.
 * ------------------------------------------------------------------------- */

/* Return the host's stored auth token for `module_name`, or NULL when the
 * module is unknown. Any NON-NULL return (including an empty string) is
 * host-allocated and the caller MUST free it with the bridge's free_fn — never
 * return a string literal. "Unknown" is signalled only by NULL. */
typedef char* (*logos_module_get_token_fn)(void* user_data,
                                           const char* module_name);

/* Inform `target` (authenticated with `target_token`) that `caller_module` may
 * call it with `new_token`. Returns 0 on success. */
typedef int (*logos_module_inform_token_fn)(void* user_data,
                                            const char* target,
                                            const char* target_token,
                                            const char* caller_module,
                                            const char* new_token);

/* Free a string the host returned from get_token. Safe on NULL. */
typedef void (*logos_module_free_fn)(void* user_data, char* s);

/* ---------------------------------------------------------------------------
 * Exported by every module cdylib (generated by the SDK of the module's
 * language; module authors never write these by hand).
 * ------------------------------------------------------------------------- */

/* Dispatch a method call. Returns the result JSON value as a heap string
 * (free with logos_module_string_free), or NULL when the method is unknown
 * or dispatch failed structurally. */
LOGOS_MODULE_IMPL_EXPORT char* logos_module_dispatch(const char* method,
                                                     const char* args_json);

/* The module's method/event metadata as a JSON array — same shape as
 * LogosProviderObject::getMethods() (entries tagged "method"/"event"). */
LOGOS_MODULE_IMPL_EXPORT char* logos_module_get_methods(void);

/* Module identity/context, stamped by the host before the first dispatch:
 * module path, instance id, per-instance persistence path. Mirrors
 * LogosModuleContext / RustModuleContext. Any argument may be NULL. */
LOGOS_MODULE_IMPL_EXPORT void logos_module_set_context(
    const char* module_path,
    const char* instance_id,
    const char* instance_persistence_path);

/* Install the host's event-emission callback. The module keeps (cb,
 * user_data) and invokes cb once per emitted event. Passing NULL clears it;
 * after the clearing call returns, the module must not invoke the old cb. */
LOGOS_MODULE_IMPL_EXPORT void logos_module_set_emit_callback(
    logos_module_emit_cb cb, void* user_data);

/* Deliver an auth token for `module_name` (the provider-side
 * informModuleToken). Returns 0 on acceptance. */
LOGOS_MODULE_IMPL_EXPORT int logos_module_accept_token(const char* module_name,
                                                       const char* token);

/* Install the host's token-bridge callbacks (see the typedefs above). Only a
 * token-authority module (capability_module, via LogosTokenManagerContext)
 * uses them; every other module ignores the bridge. Additive/opt-in: an old
 * host that never calls this leaves the bridge unset and the SDK base's
 * accessors no-op.
 *
 * Threading, matching logos_module_set_emit_callback: the module may invoke the
 * installed callbacks from ANY module thread (a concurrency:"multi" handler runs
 * on a worker), so the host implementation must be thread-safe / marshal as
 * needed. The module keeps (callbacks, user_data) until the next call replaces
 * them. Passing all-NULL clears the bridge; after that call returns the module
 * must not invoke the old pointers. */
LOGOS_MODULE_IMPL_EXPORT void logos_module_set_token_bridge(
    logos_module_get_token_fn get_token,
    logos_module_inform_token_fn inform_token,
    logos_module_free_fn free_fn,
    void* user_data);

/* The logos-protocol semver this module was compiled against. Static
 * string — do NOT free. */
LOGOS_MODULE_IMPL_EXPORT const char* logos_module_get_protocol_version(void);

/* Free a string returned by this module. Safe on NULL. */
LOGOS_MODULE_IMPL_EXPORT void logos_module_string_free(char* s);

#ifdef __cplusplus
}
#endif

#endif /* LOGOS_MODULE_IMPL_H */
